Repository ed-pilots-network/frontend, pull requests merged in 2023-06, with the labels that each got.

#14 Install Chakra into project
  .gitignore
  app/layout.tsx
  app/providers.tsx
  package.json
  yarn.lock
Labels: good first issue

#27 Dockerize the application with multi-stage variables
  .dockerignore
  .env
  .env.development.sample
  .env.production.sample
  Dockerfile
  Makefile
  README.md
  app/_components/navbar/Navbar.tsx
  app/_components/navbar/navbar.test.tsx
  app/page.client.tsx
  app/page.tsx
  docker/development/Dockerfile
  docker/development/docker-compose.yml
  docker/production/Dockerfile
  docker/production/docker-compose.yml
  next.config.js
Labels: enhancement

#29 Setup to build and push multi-stage docker images to private Nexus repo
  .github/workflows/build-deploy.yaml
  .github/workflows/checks.yaml
  Dockerfile
  docker/development/docker-compose.yml
  docker/production/docker-compose.yml
Labels: enhancement

#40 Automate screenshots for responsive testing
  .gitignore
  README.md
  package.json
  playwright.config.ts
  tests/playwright/capture-screenshots.test.ts
Labels: documentation
