Repository ed-pilots-network/frontend, pull requests merged in 2023-08, with the labels that each got.

#72 Nav tests
  app/_components/navbar/Navbar.test.tsx
  app/_components/navbar/Navbar.tsx
  app/_components/navbar/navbar.test.tsx
Labels: enhancement

#71 Fix and optimize tests and handle page width at layout level with config
  app/_components/commodities/Form.tsx
  app/_components/navbar/Navbar.tsx
  app/_components/systems/Form.tsx
  app/_config/layout.ts
  app/commodities/page.client.tsx
  app/faq/page.client.tsx
  app/layout.client.tsx
  app/playground/page.client.tsx
  app/playground/page.tsx
  app/systems/page.client.tsx
  playwright.config.ts
Labels: bug, refactor

#79 Task: Implemented barrel pattern imports across forms
  app/_components/commodities/Form.tsx
  app/_components/inputs/LandingPads.tsx
  app/_components/inputs/StationTypes.tsx
  app/_components/inputs/index.tsx
  app/_components/stations/Form.tsx
  app/_components/systems/Form.test.tsx
  app/_components/systems/Form.tsx
Labels: enhancement

#95 Sets default font weight & fixes font loading in local dev
  app/_config/theme/fonts.ts
Labels: bug
